### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Jay7c** [Jay7c/jc.time-of-day#1]
**V2.0.**

Desing.
- [ ] Separated Nodes.
- [ ] Skydome.
- [ ] Earth Perspective Support.
- [ ] Gradient Colors Support.

Atmosphere.
- [ ] Preehtam and Hoffman based.
- [ ] GPU Gems2 based.
- [ ] Gradient Atmosphere.

Deep Space.
- [ ] Panorama Deep Space.
- [ ] Panorama Stars Field.

Near Space.
- [ ] Multi Sun Disk Support.
- [ ] Multi Moons Support.

Clouds.
- [ ] Static Clouds Panorama.
- [ ] Dynamic Clouds.

Enviro.
- [ ] Fog Scattering.
- [ ] Fog Controller.
- [ ] PBR Reflections Support.
- [ ] Ambient Controller Support.
---------------------------------------------------------------------------------------------

**V2.1.**

Desing.
- [ ] Profile System.

Atmosphere.
- [ ] Precompute Atmospheric Scattering.

Deep Space.
- [ ] Procedural Deep Space.
- [ ] Procedual Stars Field.

Clouds.
- [ ] Volumetric Clouds.

...
---------------------------------------------------------------------------------------------

**V2.2.**
Weather System...
