### ISSUE TITLE
Roadmap 1.1.x

### ISSUE THREAD

**Issue by Jay7c** [Jay7c/jc.time-of-day#2]
**V1.1**
> v1.x port for godot 4. 

Atmosphere:
- [ ] Add GPU Gems2 Atmosphere for support altitude variation.

Clouds.
- [ ] Add Panorama Clouds.
- [ ] Improved Dynamic Clouds.

-------------------------------------------------------------------------------

**V1.2**
Desing:
- [ ] Profile System.
...
