### ISSUE TITLE
Roadmap 1.5.x

### ISSUE THREAD

**Issue by Jay7c** [Jay7c/jc.time-of-day#3]
**V2.0**

General.
- [ ] Godot 3.5.x Support.
- [ ] Godot 4.x Support.
- [ ] Profile System.

Atmosphere.
- [ ] Preehtam and Hoffman based.
- [ ] GPU Gems2 based.
- [ ] Gradient Atmosphere.
- [ ] PerPixel and PerVertex Support.

Deep Space.
- [ ] Panorama Deep Space.
- [ ] Panorama Stars Field.

Near Space.
- [ ] Multi Sun Disk Support.
- [ ] Multi Realistic Moons Support.

Clouds.
- [ ] Static Clouds Panorama.
- [ ] Dynamic Clouds.

Enviro.
- [ ] Fog Scattering.
- [ ] PBR Reflections Support.
- [ ] Ambient Controller Support.
---------------------------------------------------------------------------------------------

**V2.1.x**
- [ ] Weather System...
---------------------------------------------------------------------------------------------

**+**
- [ ] Full Solar System Planets Calculations.
- [ ] Procedural Deep Space.
- [ ] Procedual Stars Field.
- [ ] Precompute Atmospheric Scattering
- [ ] Volumetric Clouds.
- [ ] ...
